name: DReact CI
on:
  pull_request:
    branches: [ $default-branch ]
    types: [closed]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      APP_TITLE: App Title # Update for each app
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Module Repo
        uses: actions/checkout@v2
        with:
          repository: "BrownUniversity/dreact"
          path: dreact
          token: ${{ secrets.API_TOKEN_GITHUB }} # PAT
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install App Dependencies
        run: npm ci
        working-directory: main
      - name: Build App
        run: npm run build
        working-directory: main
      - name: Get App Slug
        run: echo "APP_SLUG=$(node -p "require('./config.js').APP_NAME")" >> $GITHUB_ENV
        working-directory: main
      - name: Copy App to Module
        run: cp main/dist/${{ env.APP_SLUG }}.js dreact/apps/${{ env.APP_SLUG }}.js
      - name: Create Pull Request in Module Repo
        id: pull-request
        uses: brownuniversity/create-pull-request@v1
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }} # PAT
          branch-name: feature/${{ env.APP_SLUG }}
          commit-message: "Update ${{ env.APP_TITLE }} app"
          title: "Update ${{ env.APP_TITLE }} app"
          description: "Changes from ${{ github.event.pull_request.html_url }}"
          draft: true
          directory: "dreact"
      - name: Comment on App Pull Request
        uses: actions/github-script@v3
        if: steps.pull-request.outputs.new-pr-url
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: "Opened ${{ steps.pull-request.outputs.new-pr-url }}"
            })
