name: DReact CI
on:
  pull-request:
    types: [closed]

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout Module Repo
        uses: actions/checkout@v2
        with:
          repository: "BrownUniversity/dreact"
          path: dreact
          token: ${{ secrets.API_TOKEN_GITHUB }} # PAT
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install App Dependencies
        run: npm ci
        working-directory: main
      - name: Build App
        run: npm run build
        working-directory: main
      - name: Copy App to Module
        run: cp main/dist/[APP_NAME].js dreact/apps/[APP_NAME].js
      - name: Create Pull Request in Module Repo
        id: pull-request
        uses: brownuniversity/create-pull-request@v1.0.15
        with:
          token: ${{ secrets.API_TOKEN_GITHUB}} # PAT
          branch-name: feature/[APP_NAME]
          commit-message: "Update [APP_NAME] app"
          title: "Update [APP_NAME] app"
          description: "Changes from $PR_URL"
          draft: true
          directory: "dreact"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Comment on App Pull Request
        uses: actions/github-script@v3
        if: env.pr_url
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: "Opened ${{ env.pr_url }}"
            })
